# Generated by Django 4.1.2 on 2022-11-06 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portafolio',
            new_name='FamiliaDataModel',
        ),
    ]
